name: Frontend Template

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      - name: git chekcout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Holo mundo
        run: |
          echo "Holo Mundo"