name: "extract file"
description: "Extract parameters from properties.json file"
inputs:
  file-path:
    description: "File path where set parameters"
    required: true
    default: "./properties.json"
outputs:
  package_manager:
    description: "Packages manager"
    value: ${{ steps.extract-and-set-properties.outputs.package_manager }}
  node_version:
    description: "Node version"
    value: ${{ steps.extract-and-set-properties.outputs.node_version }}

runs:
  using: "composite"
  steps:
    - name: "Extract and set properties"
      id: extract-and-set-properties
      shell: bash
      run: sh ./devops-templates/composite-actions/extract-file/extract-file.sh "${{ inputs.file-path }}"
