name: Frontend Template Wilson

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-template:
    runs-on: ubuntu-22.04
    steps:
      # Paso 1: Copiar el contenido del repositorio objetivo
      - name: "Step 1: Git checkout"
        uses: actions/checkout@v4

      # Paso 2: Copiar el contenido del repositorio template
      - name: "Step 2: Git checkout DevOps templates"
        uses: actions/checkout@v4
        with:
          path: "devops-templates"
          repository: Jenkins-2-actions/devops-templates
          ref: wilson

      # Paso 3: Extraer las propiedades del archivo Jenkinsfile.json
      - name: "Step 3: Set variables"
        id: set-variables
        uses: ./devops-templates/composite-actions/extract-file

      # Step de prueba
      - name: "TEST"
        run: |
          echo "${{ steps.set-variables.outputs.properties.node-version }}"
          echo "${{ github.workflow }}-${{ github.ref }}"
          node_version=$(echo "${{ steps.set-variables.outputs.properties }}" | jq -r '.["node-version"]')
          echo "Node version: $node_version"

      # Paso 4: Compilar la aplicación
      - name: "Step 4: Build app"
        uses: ./devops-templates/composite-actions/npm-build
        with:
          node-version: |
            $(echo "${{ steps.set-variables.outputs.properties }}" | jq -r '.["node-version"]')

      # Paso 5: Realizar las pruebas unitarias
      - name: "Step 5: Unit testing"
        uses: ./devops-templates/composite-actions/npm-test

      # Paso 6: Compilar la aplicación
      # Paso 7: Desplegar sobre la infraestructura
