name: Frontend Template Wilson

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      # Paso 1: Copiar el contenido del repositorio template
      - name: "Step 1: Git checkout config"
        uses: actions/checkout@v4
        with:
          repository: "Jenkins-2-actions/devops-templates"
          ref: "wilson"
          path: "./"
      # Step de prueba
      - name: "TEST"
        run: ls -al
      # Paso 2: Copiar el contenido del repositorio objetivo
      - name: "Step 2: Git checkout"
        uses: actions/checkout@v4
        with:
          path: "./"
      # Step de prueba
      - name: "TEST"
        run: ls -al
      # Paso 3: Extraer las propiedades del archivo Jenkinsfile.json
      - name: "Step 3: Set variables"
        run: echo "oli"
      # Paso 3: Configurar el entorno de ejecución
      # Paso 4: Realizar las pruebas unitarias
      # Paso 5: Compilar la aplicación
      # Paso 6: Desplegar sobre la infraestructura
      - name: "Command Test"
        run: |
          ls -lha
          ls -lha ..

      - name: Hola Action
        uses: Jenkins-2-actions/action-devops-templates@master
        with:
          who-to-greet: "Mona the Octocat"

      - name: build app
        uses: ./devops-templates/test/node-build-action.yml

  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: my-artifact
  #         path: ./

  # npm-build:
  #   needs: [frontend-tempate]
  #   uses: "Jenkins-2-actions/devops-templates/.github/workflows/node-build-action.yml@master"
