name: Frontend Template

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Git chekcout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'npm build'
        uses: "./declarative-actions/node-build-action.yml"z

      - name: Hola Action
        uses: Jenkins-2-actions/action-devops-templates@master
        with:
          who-to-greet: 'Mona the Octocat'
