name: Frontend Template Wilson

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-template:
    runs-on: ubuntu-22.04
    steps:
      # Paso 1: Copiar el contenido del repositorio objetivo
      - name: "Step 1: Git checkout"
        uses: actions/checkout@v4

      # Paso 2: Copiar el contenido del repositorio template
      - name: "Step 2: Git checkout DevOps templates"
        uses: actions/checkout@v4
        with:
          path: "devops-templates"
          repository: Jenkins-2-actions/devops-templates
          ref: wilson

      # Paso 3: Extraer las propiedades del archivo properties.json
      - name: "Step 3: Set variables"
        id: set-variables
        uses: ./devops-templates/composite-actions/extract-file

      # Paso 4: Configurar Node JS
      - name: "Step 4: Node JS config"
        uses: ./devops-templates/composite-actions/npm-config
        with:
          node-version: ${{ steps.set-variables.outputs.node_version }}

      # Paso 5: Compilar la aplicación
      - name: "Step 5: Build app"
        uses: ./devops-templates/composite-actions/npm-build

      # Paso 6: Realizar las pruebas unitarias
      - name: "Step 6: Unit testing"
        uses: ./devops-templates/composite-actions/npm-test

      # Paso 7: Análisis de Sonar
      # Paso 8: Desplegar sobre la infraestructura
