name: Frontend Template

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Git chekcout :rocket:'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Hola mundo
        run: |
          echo "Hola Mundo"