name: Frontend Template

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:      
      - name: 'Git chekcout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Git chekcout devops-templates'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: 'devops-templates'
          repository: Jenkins-2-actions/devops-templates


      - name: 'Setup variables'
        uses: Jenkins-2-actions/devops-set-up-action@master
        with:
          who-to-greet: 'Mona the Octocat'

      - name: build app
        uses: ./devops-templates/composite-actions/npm-build

      - name: Unit test 
        uses: ./devops-templates/composite-actions/npm-test

  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: my-artifact
  #         path: ./

  # npm-build:
  #   needs: [frontend-tempate] 
  #   uses: "Jenkins-2-actions/devops-templates/.github/workflows/node-build-action.yml@master"


