name: Frontend Template Wilson

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      # Paso 1: Copiar el contenido del repositorio objetivo
      - name: "Step 1: Git checkout"
        uses: actions/checkout@v4

      # Paso 2: Copiar el contenido del repositorio template
      - name: "Step 2: Template config checkout"
        run: |
          mkdir ./.github/actions/node-build
          curl -o ./.github/actions/node-build/action.yml https://raw.githubusercontent.com/Jenkins-2-actions/devops-templates/wilson/.github/workflows/node-build-action.yml
          chmod +x ./.github/actions/node-build/action.yml

      # Step de prueba
      - name: "TEST"
        run: ls -al ./.github/workflows

      # Paso 3: Extraer las propiedades del archivo Jenkinsfile.json
      - name: "Step 3: Set variables"
        run: echo "Set variables comming soon"

      # Paso 4: Configurar el entorno de ejecución
      - name: "Step 4: Run enviroment configuration"
        uses: ./.github/actions/node-build

      # Paso 4: Realizar las pruebas unitarias
      # Paso 5: Compilar la aplicación
      # Paso 6: Desplegar sobre la infraestructura

      - name: Hola Action
        uses: Jenkins-2-actions/action-devops-templates@master
        with:
          who-to-greet: "Mona the Octocat"

  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: my-artifact
  #         path: ./

  # npm-build:
  #   needs: [frontend-tempate]
  #   uses: "Jenkins-2-actions/devops-templates/.github/workflows/node-build-action.yml@master"
