name: Frontend Template

on:
  workflow_call:

jobs:
  frontend-tempate:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Git chekcout templates'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: Jenkins-2-actions/devops-templates

      - name: 'Git chekcout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Command Test'  
        run: |
          ls -lha ..

      - name: Hola Action
        uses: Jenkins-2-actions/action-devops-templates@master
        with:
          who-to-greet: 'Mona the Octocat'

      - name: build app
        uses: ./Jenkins-2-actions/devops-templates/.github/workflows/test/node-build-action.yml


  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: my-artifact
  #         path: ./

  # npm-build:
  #   needs: [frontend-tempate] 
  #   uses: "Jenkins-2-actions/devops-templates/.github/workflows/node-build-action.yml@master"


