name: npm build

jobs:
  using: "composite"
  steps:
    - name: node setup
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Npm install  
      run: npm ci
    - name: Npm test  
      run: npm test
    