name: npm build

on:
  workflow_call:

jobs:
  node-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: ./
      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: 'npm build'  
        run: |
          ls -lha
          npm ci
    